<?php
echo '<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
	<url>
		<loc>https://www.loginradius.io/</loc>
		<lastmod>2019-09-06T17:00:00Z</lastmod>
		<changefreq>monthly</changefreq>
		<priority>0.1</priority>
	</url>
	<url>
		<loc>https://www.loginradius.io/signup/</loc>
		<lastmod>2019-09-06T17:00:00Z</lastmod>
		<changefreq>monthly</changefreq>
		<priority>0.2</priority>
	</url>
	<url>
		<loc>https://www.loginradius.io/privacy-policy/</loc>
		<lastmod>2019-09-06T17:00:00Z</lastmod>
		<changefreq>monthly</changefreq>
		<priority>0.2</priority>
	</url>
	<url>
		<loc>https://www.loginradius.io/terms/</loc>
		<lastmod>2019-09-06T17:00:00Z</lastmod>
		<changefreq>monthly</changefreq>
		<priority>0.2</priority>
	</url>
</urlset>';
?>